SELECT au.AUTHOR_ID,
    au.AUTHOR_NAME,
    b.CATEGORY,
    SUM(bs.SALES * b.PRICE) TOTAL_SALES
FROM BOOK b
JOIN BOOK_SALES bs ON b.BOOK_ID=bs.BOOK_ID
JOIN author au on b.AUTHOR_ID=au.AUTHOR_ID
WHERE bs.SALES_DATE >= 202201
    AND bs.SALES_DATE < 20220201
GROUP BY 1, 3
ORDER BY 1, 3 DESC