SELECT USER_ID,
    NICKNAME,
    CONCAT(CITY, ' ', STREET_ADDRESS1,' ', STREET_ADDRESS2) as '전체주소',
    INSERT(INSERT(TLNO, 8, 0, '-'), 4, 0, '-') as '전화번호'
FROM USED_GOODS_USER
WHERE (USER_ID) IN (
    SELECT WRITER_ID
    FROM USED_GOODS_BOARD
    GROUP BY 1
    HAVING COUNT(1) >= 3
)
ORDER BY 1 DESC
