select ANIMAL_INS.ANIMAL_ID ANIMAL_ID,
    ANIMAL_INS.ANIMAL_TYPE ANIMAL_TYPE,
    ANIMAL_INS.NAME NAME
from ANIMAL_INS inner join ANIMAL_OUTS on ANIMAL_INS.ANIMAL_ID=ANIMAL_OUTS.ANIMAL_ID
where ANIMAL_INS.SEX_UPON_INTAKE like "Intact%" and ANIMAL_OUTS.SEX_UPON_OUTCOME not like "Intact%"
order by 1