SELECT DATE_FORMAT(os.SALES_DATE, '%Y') YEAR,
    CONVERT(DATE_FORMAT(os.SALES_DATE, '%m'), SIGNED) MONTH,
    ui.GENDER,
    COUNT(DISTINCT(os.USER_ID)) USERS
FROM ONLINE_SALE os
INNER JOIN USER_INFO ui
ON os.USER_ID=ui.USER_ID
WHERE ui.GENDER IS NOT NULL
GROUP BY 1, 2, 3