SET @user_count_2021 := (SELECT COUNT(*) AS COUNT FROM USER_INFO WHERE YEAR(JOINED) = 2021);

SELECT YEAR(os.SALES_DATE) AS YEAR,
    MONTH(os.SALES_DATE) AS MONTH,
    COUNT(DISTINCT os.USER_ID) PURCHASED_USER,
    ROUND(COUNT(DISTINCT os.USER_ID) / @user_count_2021, 1) PURCHASED_RATIO
FROM ONLINE_SALE os
JOIN USER_INFO ui
    ON os.USER_ID = ui.USER_ID
WHERE YEAR(ui.JOINED) = 2021
GROUP BY 1, 2