WITH users_2021 AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE JOINED >= 20210101
        AND JOINED < 20220101
),
users_count_2021 AS (
    SELECT COUNT(*) AS COUNT
    FROM users_2021
)

SELECT YEAR,
    MONTH,
    PURCHASED_USER,
    ROUND(PURCHASED_USER / (SELECT COUNT FROM users_count_2021), 1) PURCHASED_RATIO
FROM (
    SELECT YEAR(SALES_DATE) AS YEAR,
        MONTH(SALES_DATE) AS MONTH,
        COUNT(DISTINCT USER_ID) PURCHASED_USER
    FROM ONLINE_SALE
    WHERE USER_ID IN (SELECT USER_ID FROM users_2021)
    GROUP BY 1, 2
) a