SELECT fp.PRODUCT_ID,
    fp.PRODUCT_NAME,
    SUM(fo.AMOUNT * fp.PRICE) as TOTAL_SALES
FROM FOOD_PRODUCT as fp
INNER JOIN FOOD_ORDER as fo
ON fp.PRODUCT_ID=fo.PRODUCT_ID
WHERE DATE_FORMAT(fo.PRODUCE_DATE, '%y%m') LIKE 2205
GROUP BY fp.PRODUCT_ID
ORDER BY 3 DESC, 1