SELECT ap.APNT_NO,
    pt.PT_NAME,
    pt.PT_NO,
    ap.MCDP_CD,
    dr.DR_NAME,
    ap.APNT_YMD
FROM PATIENT pt, DOCTOR dr, APPOINTMENT ap
WHERE pt.PT_NO=ap.PT_NO AND dr.DR_ID=ap.MDDR_ID
    AND DATE(ap.APNT_YMD)=20220413 AND ap.APNT_CNCL_YN='N'
ORDER BY 6