WITH RECURSIVE HOURS AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM HOURS
    WHERE HOUR < 23
)

SELECT h.HOUR,
    COALESCE(a.COUNT, 0) AS COUNT
FROM HOURS h
LEFT JOIN (
    SELECT HOUR(DATETIME) AS HOUR,
        COUNT(1) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY 1
) a
ON h.HOUR=a.HOUR
ORDER BY HOUR