SELECT MEMBER_ID,
    MEMBER_NAME,
    GENDER,
    DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE TLNO IS NOT NULL
    AND GENDER LIKE 'W'
    AND DATE_FORMAT(DATE_OF_BIRTH, '%m') like '03'
ORDER BY 1