SELECT BOARD_ID,
    WRITER_ID,
    TITLE,
    PRICE,
    CASE WHEN STATUS LIKE 'SALE' THEN '판매중'
        WHEN STATUS LIKE 'DONE' THEN '거래완료'
        ELSE '예약중' END STATUS
FROM USED_GOODS_BOARD
WHERE CREATED_DATE=20221005
ORDER BY 1 DESC